### ISSUE TITLE
[Question] About Gun

### ISSUE THREAD

**Issue by yordis** [NFIBrokerage/spear#66]
> That project looks good but it depends on [:gun](https://github.com/ninenines/gun) which doesn't play nice with other dependencies.

Hey peeps, I am curious to learn from your experience about such a statement. Do you mind expanding fo what was the issue with `:gun`?

Thank you in advance.

**Comment by yordis** [comment]
Ah!!! I see I see the problems ahead, I keep forgetting about such problems until I ran into them.

Thank you so much for the explanation.

**Comment by yordis** [comment]
@the-mikedavis the new [elixir-grpc/grpc](https://github.com/elixir-grpc/grpc) allows to use Mint over Gun.

For the sake of alignment in the ecosystem and helping each other.

Is it prudent to give it a second try to the gprc package? Are you open to it if the solution is good? (whatever that means to you)

**Comment by the-mikedavis** [comment]
Oh cool, I'm glad to see `grpc` pick up Mint support, I think that will be a big improvement for using gRPC in Elixir 🚀

I took a look at the PR that added Mint support. The two things I was mostly looking at were the handling of concurrent requests, so that Spear can append many events and stream many subscriptions all though one connection process, and sending very large messages/streams. The concurrent stuff looks good. The streaming support is better in Spear though: from what I can tell, `grpc` will send a message to the connection process for every message it wants to send in a stream. In Spear we unfold streams within the connection process and fit as many messages into a frame as possible. This ends up taking only one Erlang message since we just hand over the stream to the connection process vs one Erlang message per gRPC message. I would worry about the performance of many appends suffering but this would need to be tested. Also see #3 and https://github.com/sneako/finch/pull/158.

Looking around the rest of the codebase though, there are a few reasons I don't want to add in `grpc`:

* It bundles client and server functionality into one library. Spear only needs a client and the rest would just be bloat.
* `grpc` has non-optional dependencies on a bunch of rather large libraries like cowboy and their fork of `gun`'s 2.0 release line: https://github.com/elixir-grpc/grpc/blob/7bd40696582fb5e6640ea846d4f6989e6d754fa4/mix.exs#L42-L47. So even though you can use Mint at runtime now, they still depend on `gun` which is a problem.
* The Mint adapter uses an extra process for response streams which isn't necessary for Spear: https://github.com/elixir-grpc/grpc/blob/7bd40696582fb5e6640ea846d4f6989e6d754fa4/lib/grpc/client/adapters/mint/stream_response_process.ex

Mainly I want to keep the dependency tree for Spear very small. The existing spear dependencies should be compatible with `grpc`'s dependency list. It would be a really big change in Spear to switch to `grpc` so I would like to only do that if there's a big problem with using Mint directly

**Comment by yordis** [comment]
Is it worth connecting with them and discussing your pain points?

I am trying to allocate some budget and energy to create a better foundation across the ecosystem. Some points could be addressed and improved in the gRPC package.

**Comment by the-mikedavis** [comment]
I think that Spear is too niche of a use-case to justify spending effort making the `grpc` integration perfect for it. Spear wants really low-level control over gRPC details so even if `grpc` satisfied all of my nitpicks I would probably still not use it in an effort to keep really fine-grained control over the connection and also keep the dependency tree small.

I haven't used gRPC outside of this client or in other languages so I'm not sure what's missing for a really nice experience. I think it is probably best to survey what typical gRPC users want to see in the ecosystem.
